### ISSUE TITLE
Getting an reflections exception when committing a composition with EVENT

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase_client_library#32]
This exception is thrown when building and committing the composition for the Laborbefund template, though the composition is being generated and committed correctly:

```
2020-04-30 23:26:47.057  WARN 23575 --- [o-auto-1-exec-7] org.reflections.Reflections              : could not get type for name com.nedap.archie.rm.datastructures.Event<Type> from any class loader

org.reflections.ReflectionsException: could not get type for name com.nedap.archie.rm.datastructures.Event<Type>
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:na]
	at org.ehrbase.client.flattener.Unflattener.unwarap(Unflattener.java:193) ~[client-library-0.3.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548) ~[na:na]
	at org.ehrbase.client.flattener.Unflattener.extractType(Unflattener.java:213) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.handleSingleValue(Unflattener.java:167) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.setValueAtPath(Unflattener.java:106) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.lambda$mapDtoToEntity$1(Unflattener.java:84) ~[client-library-0.3.0.jar:na]
	at java.base/java.util.HashMap.forEach(HashMap.java:1336) ~[na:na]
	at org.ehrbase.client.flattener.Unflattener.mapDtoToEntity(Unflattener.java:84) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.handleSingleValue(Unflattener.java:181) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.setValueAtPath(Unflattener.java:106) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.lambda$mapDtoToEntity$1(Unflattener.java:84) ~[client-library-0.3.0.jar:na]
	at java.base/java.util.HashMap.forEach(HashMap.java:1336) ~[na:na]
	at org.ehrbase.client.flattener.Unflattener.mapDtoToEntity(Unflattener.java:84) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.unflatten(Unflattener.java:78) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.openehrclient.defaultrestclient.DefaultRestCompositionEndpoint.mergeCompositionEntity(DefaultRestCompositionEndpoint.java:51) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.fhirbridge.rest.EhrbaseService.saveLab(EhrbaseService.java:29) ~[fhir-bridge-1.0.0-SNAPSHOT.jar:na]
	at org.ehrbase.fhirbridge.fhir.provider.ObservationResourceProvider.createObservation(ObservationResourceProvider.java:53) ~[fhir-bridge-1.0.0-SNAPSHOT.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:239) ~[hapi-fhir-server-4.2.0.jar:na]
	at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154) ~[hapi-fhir-server-4.2.0.jar:na]
	at ca.uhn.fhir.rest.server.method.CreateMethodBinding.invokeServer(CreateMethodBinding.java:41) ~[hapi-fhir-server-4.2.0.jar:na]
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1002) ~[hapi-fhir-server-4.2.0.jar:na]
	at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:346) ~[hapi-fhir-server-4.2.0.jar:na]
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1701) ~[hapi-fhir-server-4.2.0.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.33.jar:9.0.33]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.ClassNotFoundException: com.nedap.archie.rm.datastructures.Event<Type>
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:na]
	... 70 common frames omitted
```

**Comment by ppazos** [comment]
@Geisterfalle this is the only exception left in the FHIR bridge, not sure if it's possible to update the archie version in the SDK to check for a fix, when I tried some time ago it generated an issue with the reflection library which broke the build.
Even though the exception appears in the terminal, it doesn't affect the bridge functionally.

**Comment by ppazos** [comment]
2020-07-28: re-tested for https://github.com/ehrbase/project_management/issues/319

This is still appearing in the terminal running the FHIR bridge when a FHIR resource is submitted, mapped to an openEHR compo, and that compo committed to EHRBASE.

**Comment by stefanspiska** [comment]
@ppazos 
can you retest with https://github.com/ehrbase/openEHR_SDK/tree/release/v1.0.0
