### ISSUE TITLE
Warnings in OptSkeletonBuilder

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase_client_library#33]
When working in the fhir-bridge, I see a lot of warnings, I guess this is when an object is serialized to JSON but I'm not 100% sure, it seems it is trying to access a template_id attribute not all classes have, not sure why.

> 
> 2020-05-07 00:42:37.576  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvCodedText
> 2020-05-07 00:42:37.587  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.600  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.604  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.610  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.614  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.616  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.621  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Cluster
> 2020-05-07 00:42:37.633  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object ItemTree
> 2020-05-07 00:42:37.641  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object EventContext
> 2020-05-07 00:42:37.675  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvCodedText
> 2020-05-07 00:42:37.688  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.695  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.712  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.716  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.719  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.736  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.744  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.750  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.756  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.757  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.798  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.810  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.817  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.828  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvCodedText
> 2020-05-07 00:42:37.839  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.851  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.851  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Cluster
> 2020-05-07 00:42:37.861  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvDateTime
> 2020-05-07 00:42:37.870  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.881  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.886  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.898  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvDateTime
> 2020-05-07 00:42:37.908  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.914  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.916  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.917  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvCodedText
> 2020-05-07 00:42:37.922  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.924  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.942  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.949  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.952  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.954  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:37.954  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.954  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.955  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvBoolean
> 2020-05-07 00:42:37.959  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.959  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.960  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvBoolean
> 2020-05-07 00:42:37.976  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:37.983  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:37.989  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Cluster
> 2020-05-07 00:42:38.015  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvCodedText
> 2020-05-07 00:42:38.021  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:38.026  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:38.028  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:38.032  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:38.033  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:38.034  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Cluster
> 2020-05-07 00:42:38.039  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvDateTime
> 2020-05-07 00:42:38.048  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:38.052  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:38.061  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvCodedText
> 2020-05-07 00:42:38.062  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:38.063  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:38.063  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:38.064  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:38.068  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:38.069  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:38.078  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object ItemTree
> 2020-05-07 00:42:38.080  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvDateTime
> 2020-05-07 00:42:38.083  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object DvText
> 2020-05-07 00:42:38.083  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : null
> 2020-05-07 00:42:38.084  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Element
> 2020-05-07 00:42:38.085  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object ItemTree
> 2020-05-07 00:42:38.089  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Evaluation
> 2020-05-07 00:42:38.096  WARN 10398 --- [o-auto-1-exec-7] o.e.client.building.OptSkeletonBuilder   : Attribute template_id not known for object Composition

**Comment by Xelpha** [comment]
I tried to use the TriageAssessment composition in CKM and I was able to build it using the class generator. However when I try to submit a composition to ehrbase I get the following error:

> java.lang.NoSuchMethodError: com.nedap.archie.rm.datatypes.CodePhrase.<init>(Lcom/nedap/archie/rm/support/identification/TerminologyId;Ljava/lang/String;)V
	at org.ehrbase.terminology.openehr.implementation.SimpleTerminologyAccess.addGroup(SimpleTerminologyAccess.java:76) ~[terminology-0.11.0.jar:0.11.0]
	at org.ehrbase.terminology.openehr.implementation.SimpleTerminologyInterface.loadTerminologies(SimpleTerminologyInterface.java:129) ~[terminology-0.11.0.jar:0.11.0]
	at org.ehrbase.terminology.openehr.implementation.SimpleTerminologyInterface.<init>(SimpleTerminologyInterface.java:99) ~[terminology-0.11.0.jar:0.11.0]
	at org.ehrbase.terminology.openehr.implementation.LocalizedTerminologies.<init>(LocalizedTerminologies.java:32) ~[terminology-0.11.0.jar:0.11.0]
	at org.ehrbase.client.building.OptSkeletonBuilder.<clinit>(OptSkeletonBuilder.java:70) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.flattener.Unflattener.<clinit>(Unflattener.java:65) ~[client-library-0.3.0.jar:na]
	at org.ehrbase.client.openehrclient.defaultrestclient.DefaultRestCompositionEndpoint.mergeCompositionEntity(DefaultRestCompositionEndpoint.java:51) ~[client-library-0.3.0.jar:na]

**Comment by ppazos** [comment]
2020-07-28: Retested for https://github.com/ehrbase/project_management/issues/319

This is still appearing in the terminal running the FHIR bridge when a FHIR resource is submitted, mapped to an openEHR compo, and that compo committed to EHRBASE.

**Comment by stefanspiska** [comment]
@ppazos 
Can you retest with  https://github.com/ehrbase/openEHR_SDK/tree/release/v1.0.0
This should have been fixed a long time ago.
